services:
  backend_counter_stagingapp:
    build:
      context: ./backend/
      dockerfile: ./counter/Dockerfile
    environment:
      CONFIG_ENV: staging
      CONFIG_PATH: /app/config.staging.toml
      ENV_PATH: /app/.env.staging
    volumes:
      - ./config.staging.toml:/app/config.staging.toml:ro
      - ./.env.staging:/app/.env.staging:ro
    restart: unless-stopped
    networks:
      - staging_network

  backend_cleanup_stagingapp:
    build:
      context: ./backend/
      dockerfile: ./cleanup/Dockerfile
    environment:
      CONFIG_ENV: staging
      CONFIG_PATH: /app/config.staging.toml
      ENV_PATH: /app/.env.staging
    volumes:
      - ./config.staging.toml:/app/config.staging.toml:ro
      - ./.env.staging:/app/.env.staging:ro
    restart: unless-stopped
    networks:
      - staging_network

  frontend_stagingapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_APIURL: "https://testingapp.sumcrowds.com/api/"
        VITE_WSURL: "wss://testingapp.sumcrowds.com/ws/"
    restart: unless-stopped
    networks:
      - staging_network

  nginx_stagingproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "40000:80"
    restart: unless-stopped
    networks:
      - staging_network
    depends_on:
      - backend_counter_stagingapp
      - frontend_stagingapp
    command: ["nginx", "-g", "daemon off;"]

networks:
  staging_network:
    driver: bridge
