services:
  backend_counter_app:
    build:
      context: ./backend/
      dockerfile: ./counter/Dockerfile
    env_file:
      - back.env.prod
    restart: unless-stopped
    networks:
      - prod_network

  backend_cleanup_app:
    build:
      context: ./backend/
      dockerfile: ./cleanup/Dockerfile
    env_file:
      - cleanup.env.prod
    restart: unless-stopped
    networks:
      - prod_network


  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_APIURL: "https://sumcrowds.com/api/"
        VITE_WSURL: "wss://sumcrowds.com/ws/"
    restart: unless-stopped
    networks:
      - prod_network

  nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "40001:80"
    restart: unless-stopped
    networks:
      - prod_network
    depends_on:
      - backend_counter_app
      - frontend_app
    command: ["nginx", "-g", "daemon off;"]

networks:
  prod_network:
    driver: bridge
