services:
  backend_devapp:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8080
      - ORIGIN=https://testing.sumcrowds.com
    restart: unless-stopped
    networks:
      - dev_network
    volumes:
      - dev_backend_data:/app/data 

  frontend_devapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_APIURL: "https://testing.sumcrowds.com/api/"
        VITE_WSURL: "wss://testing.sumcrowds.com/ws/"
    env_file:
      - front.env.dev
    restart: unless-stopped
    networks:
      - dev_network

  nginx_devproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "40000:80"
    restart: unless-stopped
    networks:
      - dev_network
    depends_on:
      - backend_devapp
      - frontend_devapp
    command: ["nginx", "-g", "daemon off;"]

networks:
  dev_network:
    driver: bridge

volumes:
  dev_backend_data:
