services:
  backend_devapp:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - back.env.dev
    restart: unless-stopped
    networks:
      - dev_network

  frontend_devapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_APIURL: "https://testing.sumcrowds.com/api/"
        VITE_WSURL: "wss://testing.sumcrowds.com/ws/"
    restart: unless-stopped
    networks:
      - dev_network

  nginx_devproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "40000:80"
    restart: unless-stopped
    networks:
      - dev_network
    depends_on:
      - backend_devapp
      - frontend_devapp
    command: ["nginx", "-g", "daemon off;"]

networks:
  dev_network:
    driver: bridge
