name: Build the packages/containers
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: git.thyamix.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push package
        run : |
          GIT_COMMIT_SHA=${{ env.GITHUB_SHA }}
          GIT_COMMIT_SHA=${GIT_COMMIT_SHA::10}

          docker compose -f docker-compose.kubernetes.yaml build

          IMAGES=(
            "git.thyamix.com/thyamix/sumcrowds-counter"
            "git.thyamix.com/thyamix/sumcrowds-cleanup"
            "git.thyamix.com/thyamix/sumcrowds-frontend"
          )

          for IMAGE in "${IMAGES[@]}"; do
            docker tag $IMAGE:$GIT_COMMIT_SHA $IMAGE:latest
            docker push $IMAGE:$GIT_COMMIT_SHA
            docker push $IMAGE:latest
          done

