name: Deploy to Server
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: push package
      run : |
        GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
        docker compose -f docker-compose.kubernetes.yaml build
        docker compose -f docker-compose.kubernetes.yaml push
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no thyamix@${{ secrets.DEPLOY_IP }} "\
            cd /home/thyamix/Programming/project/sumcrowds && \
            git pull origin master && \
            docker compose -f docker-compose.prod.yaml down && \
            docker compose -f docker-compose.prod.yaml up --build -d"
      
      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key
