// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package sqlcdb

import (
	"context"
)

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :exec
DELETE FROM access_token WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context, expiresAt int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredAccessTokens, expiresAt)
	return err
}

const deleteExpiredEvents = `-- name: DeleteExpiredEvents :exec
DELETE FROM event WHERE last_used_at < $1
`

func (q *Queries) DeleteExpiredEvents(ctx context.Context, lastUsedAt int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredEvents, lastUsedAt)
	return err
}

const deleteExpiredFestivalAccess = `-- name: DeleteExpiredFestivalAccess :exec
DELETE FROM festival_access WHERE last_used_at < $1
`

func (q *Queries) DeleteExpiredFestivalAccess(ctx context.Context, lastUsedAt int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredFestivalAccess, lastUsedAt)
	return err
}

const deleteExpiredFestivals = `-- name: DeleteExpiredFestivals :exec
DELETE FROM festival WHERE last_used_at < $1
`

func (q *Queries) DeleteExpiredFestivals(ctx context.Context, lastUsedAt int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredFestivals, lastUsedAt)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_token WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}
