// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveActiveToArchive = `-- name: ArchiveActiveToArchive :exec
INSERT INTO archive (value, time, event_id)
SELECT active.value, active.time, active.event_id FROM active WHERE active.event_id = $1
`

func (q *Queries) ArchiveActiveToArchive(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, archiveActiveToArchive, eventID)
	return err
}

const checkEventExists = `-- name: CheckEventExists :one
SELECT COUNT(1) FROM event WHERE id = $1
`

func (q *Queries) CheckEventExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, checkEventExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveEntries = `-- name: CountActiveEntries :one
SELECT COUNT(*) FROM active WHERE event_id = $1
`

func (q *Queries) CountActiveEntries(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEntries, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchiveEntries = `-- name: CountArchiveEntries :one
SELECT COUNT(*) FROM archive WHERE event_id = $1
`

func (q *Queries) CountArchiveEntries(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countArchiveEntries, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (created_at, last_used_at, festival_id, active, total)
VALUES ($1, $1, $2, TRUE, 0) RETURNING id
`

type CreateEventParams struct {
	CreatedAt  int64 `json:"created_at"`
	FestivalID int64 `json:"festival_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.CreatedAt, arg.FestivalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deactivateEvent = `-- name: DeactivateEvent :exec
UPDATE event SET active = FALSE, last_used_at = $1 WHERE id = $2
`

type DeactivateEventParams struct {
	LastUsedAt int64 `json:"last_used_at"`
	ID         int64 `json:"id"`
}

func (q *Queries) DeactivateEvent(ctx context.Context, arg DeactivateEventParams) error {
	_, err := q.db.Exec(ctx, deactivateEvent, arg.LastUsedAt, arg.ID)
	return err
}

const deleteActiveByEventId = `-- name: DeleteActiveByEventId :exec
DELETE FROM active WHERE event_id = $1
`

func (q *Queries) DeleteActiveByEventId(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, deleteActiveByEventId, eventID)
	return err
}

const getActiveEntriesChunk = `-- name: GetActiveEntriesChunk :many
SELECT a.value, a.time,
  COALESCE((SELECT gm.gauge_max FROM gauge_max gm
    WHERE gm.event_id = a.event_id AND gm.time <= a.time
    ORDER BY gm.time DESC LIMIT 1), 0) AS current_gauge_max
FROM active a WHERE a.event_id = $1
ORDER BY a.id LIMIT $2 OFFSET $3
`

type GetActiveEntriesChunkParams struct {
	EventID int64 `json:"event_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetActiveEntriesChunkRow struct {
	Value           int32       `json:"value"`
	Time            int64       `json:"time"`
	CurrentGaugeMax interface{} `json:"current_gauge_max"`
}

func (q *Queries) GetActiveEntriesChunk(ctx context.Context, arg GetActiveEntriesChunkParams) ([]GetActiveEntriesChunkRow, error) {
	rows, err := q.db.Query(ctx, getActiveEntriesChunk, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveEntriesChunkRow
	for rows.Next() {
		var i GetActiveEntriesChunkRow
		if err := rows.Scan(&i.Value, &i.Time, &i.CurrentGaugeMax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveEventIdByFestivalCode = `-- name: GetActiveEventIdByFestivalCode :one
SELECT e.id FROM event e
JOIN festival f ON f.id = e.festival_id
WHERE e.active = TRUE AND f.code = $1
`

func (q *Queries) GetActiveEventIdByFestivalCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveEventIdByFestivalCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveEventIdByFestivalId = `-- name: GetActiveEventIdByFestivalId :one
SELECT id FROM event WHERE active = TRUE AND festival_id = $1
`

func (q *Queries) GetActiveEventIdByFestivalId(ctx context.Context, festivalID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveEventIdByFestivalId, festivalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getArchiveEntriesChunk = `-- name: GetArchiveEntriesChunk :many
SELECT ar.value, ar.time,
  COALESCE((SELECT gm.gauge_max FROM gauge_max gm
    WHERE gm.event_id = ar.event_id AND gm.time <= ar.time
    ORDER BY gm.time DESC LIMIT 1), 0) AS current_gauge_max
FROM archive ar WHERE ar.event_id = $1
ORDER BY ar.id LIMIT $2 OFFSET $3
`

type GetArchiveEntriesChunkParams struct {
	EventID int64 `json:"event_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetArchiveEntriesChunkRow struct {
	Value           int32       `json:"value"`
	Time            int64       `json:"time"`
	CurrentGaugeMax interface{} `json:"current_gauge_max"`
}

func (q *Queries) GetArchiveEntriesChunk(ctx context.Context, arg GetArchiveEntriesChunkParams) ([]GetArchiveEntriesChunkRow, error) {
	rows, err := q.db.Query(ctx, getArchiveEntriesChunk, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveEntriesChunkRow
	for rows.Next() {
		var i GetArchiveEntriesChunkRow
		if err := rows.Scan(&i.Value, &i.Time, &i.CurrentGaugeMax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedEventIds = `-- name: GetArchivedEventIds :many
SELECT id, last_used_at FROM event
WHERE active = FALSE AND festival_id = $1
ORDER BY id DESC
`

type GetArchivedEventIdsRow struct {
	ID         int64 `json:"id"`
	LastUsedAt int64 `json:"last_used_at"`
}

func (q *Queries) GetArchivedEventIds(ctx context.Context, festivalID int64) ([]GetArchivedEventIdsRow, error) {
	rows, err := q.db.Query(ctx, getArchivedEventIds, festivalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivedEventIdsRow
	for rows.Next() {
		var i GetArchivedEventIdsRow
		if err := rows.Scan(&i.ID, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGaugeMax = `-- name: GetLatestGaugeMax :one
SELECT gauge_max FROM gauge_max
WHERE event_id = $1
ORDER BY time DESC LIMIT 1
`

func (q *Queries) GetLatestGaugeMax(ctx context.Context, eventID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestGaugeMax, eventID)
	var gauge_max int32
	err := row.Scan(&gauge_max)
	return gauge_max, err
}

const getTotalFromEvent = `-- name: GetTotalFromEvent :one
SELECT total FROM event WHERE id = $1
`

func (q *Queries) GetTotalFromEvent(ctx context.Context, id int64) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getTotalFromEvent, id)
	var total pgtype.Int4
	err := row.Scan(&total)
	return total, err
}

const insertActiveValue = `-- name: InsertActiveValue :exec
INSERT INTO active (value, time, event_id) VALUES ($1, $2, $3)
`

type InsertActiveValueParams struct {
	Value   int32 `json:"value"`
	Time    int64 `json:"time"`
	EventID int64 `json:"event_id"`
}

func (q *Queries) InsertActiveValue(ctx context.Context, arg InsertActiveValueParams) error {
	_, err := q.db.Exec(ctx, insertActiveValue, arg.Value, arg.Time, arg.EventID)
	return err
}

const insertGaugeMax = `-- name: InsertGaugeMax :exec
INSERT INTO gauge_max (gauge_max, time, event_id) VALUES ($1, $2, $3)
`

type InsertGaugeMaxParams struct {
	GaugeMax int32 `json:"gauge_max"`
	Time     int64 `json:"time"`
	EventID  int64 `json:"event_id"`
}

func (q *Queries) InsertGaugeMax(ctx context.Context, arg InsertGaugeMaxParams) error {
	_, err := q.db.Exec(ctx, insertGaugeMax, arg.GaugeMax, arg.Time, arg.EventID)
	return err
}

const updateEventLastUsedAt = `-- name: UpdateEventLastUsedAt :exec
UPDATE event SET last_used_at = $1 WHERE id = $2
`

type UpdateEventLastUsedAtParams struct {
	LastUsedAt int64 `json:"last_used_at"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateEventLastUsedAt(ctx context.Context, arg UpdateEventLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateEventLastUsedAt, arg.LastUsedAt, arg.ID)
	return err
}

const updateEventTotal = `-- name: UpdateEventTotal :exec
UPDATE event SET total = total + $1 WHERE id = $2
`

type UpdateEventTotalParams struct {
	Total pgtype.Int4 `json:"total"`
	ID    int64       `json:"id"`
}

func (q *Queries) UpdateEventTotal(ctx context.Context, arg UpdateEventTotalParams) error {
	_, err := q.db.Exec(ctx, updateEventTotal, arg.Total, arg.ID)
	return err
}
