// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: festival.sql

package sqlcdb

import (
	"context"
)

const createFestival = `-- name: CreateFestival :one
INSERT INTO festival (code, password, pin, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $4) RETURNING id
`

type CreateFestivalParams struct {
	Code      string `json:"code"`
	Password  string `json:"password"`
	Pin       string `json:"pin"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateFestival(ctx context.Context, arg CreateFestivalParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFestival,
		arg.Code,
		arg.Password,
		arg.Pin,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFestival = `-- name: GetFestival :one
SELECT id, last_used_at, created_at, pin, password, code
FROM festival WHERE code = $1
`

type GetFestivalRow struct {
	ID         int64  `json:"id"`
	LastUsedAt int64  `json:"last_used_at"`
	CreatedAt  int64  `json:"created_at"`
	Pin        string `json:"pin"`
	Password   string `json:"password"`
	Code       string `json:"code"`
}

func (q *Queries) GetFestival(ctx context.Context, code string) (GetFestivalRow, error) {
	row := q.db.QueryRow(ctx, getFestival, code)
	var i GetFestivalRow
	err := row.Scan(
		&i.ID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Pin,
		&i.Password,
		&i.Code,
	)
	return i, err
}

const isFestivalCodeExists = `-- name: IsFestivalCodeExists :one
SELECT EXISTS(SELECT 1 FROM festival WHERE code = $1)
`

func (q *Queries) IsFestivalCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, isFestivalCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateFestivalLastUsedAt = `-- name: UpdateFestivalLastUsedAt :exec
UPDATE festival SET last_used_at = $1 WHERE id = $2
`

type UpdateFestivalLastUsedAtParams struct {
	LastUsedAt int64 `json:"last_used_at"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateFestivalLastUsedAt(ctx context.Context, arg UpdateFestivalLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateFestivalLastUsedAt, arg.LastUsedAt, arg.ID)
	return err
}
