// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    int64  `json:"user_id"`
	Revoked   bool   `json:"revoked"`
}

type Active struct {
	ID      int64 `json:"id"`
	Value   int32 `json:"value"`
	Time    int64 `json:"time"`
	EventID int64 `json:"event_id"`
}

type AppUser struct {
	ID int64 `json:"id"`
}

type Archive struct {
	ID      int64 `json:"id"`
	Value   int32 `json:"value"`
	Time    int64 `json:"time"`
	EventID int64 `json:"event_id"`
}

type Event struct {
	ID         int64       `json:"id"`
	Active     bool        `json:"active"`
	CreatedAt  int64       `json:"created_at"`
	LastUsedAt int64       `json:"last_used_at"`
	FestivalID int64       `json:"festival_id"`
	Total      pgtype.Int4 `json:"total"`
}

type Festival struct {
	ID         int64  `json:"id"`
	LastUsedAt int64  `json:"last_used_at"`
	CreatedAt  int64  `json:"created_at"`
	Pin        string `json:"pin"`
	Code       string `json:"code"`
	Password   string `json:"password"`
}

type FestivalAccess struct {
	ID         int64 `json:"id"`
	LastUsedAt int64 `json:"last_used_at"`
	UserID     int64 `json:"user_id"`
	FestivalID int64 `json:"festival_id"`
	Revoked    bool  `json:"revoked"`
}

type GaugeMax struct {
	ID       int64 `json:"id"`
	GaugeMax int32 `json:"gauge_max"`
	Time     int64 `json:"time"`
	EventID  int64 `json:"event_id"`
}

type RefreshToken struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    int64  `json:"user_id"`
	Revoked   bool   `json:"revoked"`
}
