// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveActiveToArchive(ctx context.Context, eventID int64) error
	CheckEventExists(ctx context.Context, id int64) (int64, error)
	CountActiveEntries(ctx context.Context, eventID int64) (int64, error)
	CountArchiveEntries(ctx context.Context, eventID int64) (int64, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error)
	CreateFestival(ctx context.Context, arg CreateFestivalParams) (int64, error)
	CreateFestivalAccess(ctx context.Context, arg CreateFestivalAccessParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context) (int64, error)
	DeactivateEvent(ctx context.Context, arg DeactivateEventParams) error
	DeleteAccessToken(ctx context.Context, token string) error
	DeleteActiveByEventId(ctx context.Context, eventID int64) error
	DeleteExpiredAccessTokens(ctx context.Context, expiresAt int64) error
	DeleteExpiredEvents(ctx context.Context, lastUsedAt int64) error
	DeleteExpiredFestivalAccess(ctx context.Context, lastUsedAt int64) error
	DeleteExpiredFestivals(ctx context.Context, lastUsedAt int64) error
	DeleteExpiredRefreshTokens(ctx context.Context, expiresAt int64) error
	DeleteRefreshToken(ctx context.Context, token string) error
	GetAccessToken(ctx context.Context, token string) (AccessToken, error)
	GetActiveEntriesChunk(ctx context.Context, arg GetActiveEntriesChunkParams) ([]GetActiveEntriesChunkRow, error)
	GetActiveEventIdByFestivalCode(ctx context.Context, code string) (int64, error)
	GetActiveEventIdByFestivalId(ctx context.Context, festivalID int64) (int64, error)
	GetArchiveEntriesChunk(ctx context.Context, arg GetArchiveEntriesChunkParams) ([]GetArchiveEntriesChunkRow, error)
	GetArchivedEventIds(ctx context.Context, festivalID int64) ([]GetArchivedEventIdsRow, error)
	GetFestival(ctx context.Context, code string) (GetFestivalRow, error)
	GetFestivalAccess(ctx context.Context, arg GetFestivalAccessParams) (GetFestivalAccessRow, error)
	GetLatestGaugeMax(ctx context.Context, eventID int64) (int32, error)
	GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error)
	GetTotalFromEvent(ctx context.Context, id int64) (pgtype.Int4, error)
	GetUserIdFromAccessToken(ctx context.Context, token string) (int64, error)
	GetUserRecentSessions(ctx context.Context, arg GetUserRecentSessionsParams) ([]GetUserRecentSessionsRow, error)
	InsertActiveValue(ctx context.Context, arg InsertActiveValueParams) error
	InsertGaugeMax(ctx context.Context, arg InsertGaugeMaxParams) error
	IsFestivalCodeExists(ctx context.Context, code string) (bool, error)
	UpdateAccessToken(ctx context.Context, arg UpdateAccessTokenParams) error
	UpdateEventLastUsedAt(ctx context.Context, arg UpdateEventLastUsedAtParams) error
	UpdateEventTotal(ctx context.Context, arg UpdateEventTotalParams) error
	UpdateFestivalAccessLastUsedAt(ctx context.Context, arg UpdateFestivalAccessLastUsedAtParams) error
	UpdateFestivalLastUsedAt(ctx context.Context, arg UpdateFestivalLastUsedAtParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
