// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcdb

import (
	"context"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_token (token, expires_at, user_id, revoked)
VALUES ($1, $2, $3, $4)
`

type CreateAccessTokenParams struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    int64  `json:"user_id"`
	Revoked   bool   `json:"revoked"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken,
		arg.Token,
		arg.ExpiresAt,
		arg.UserID,
		arg.Revoked,
	)
	return err
}

const createFestivalAccess = `-- name: CreateFestivalAccess :exec
INSERT INTO festival_access (festival_id, user_id, last_used_at, revoked)
VALUES ($1, $2, $3, $4)
`

type CreateFestivalAccessParams struct {
	FestivalID int64 `json:"festival_id"`
	UserID     int64 `json:"user_id"`
	LastUsedAt int64 `json:"last_used_at"`
	Revoked    bool  `json:"revoked"`
}

func (q *Queries) CreateFestivalAccess(ctx context.Context, arg CreateFestivalAccessParams) error {
	_, err := q.db.Exec(ctx, createFestivalAccess,
		arg.FestivalID,
		arg.UserID,
		arg.LastUsedAt,
		arg.Revoked,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (token, expires_at, user_id, revoked)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    int64  `json:"user_id"`
	Revoked   bool   `json:"revoked"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Token,
		arg.ExpiresAt,
		arg.UserID,
		arg.Revoked,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM access_token WHERE token = $1
`

func (q *Queries) DeleteAccessToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteAccessToken, token)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_token WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, token, expires_at, user_id, revoked
FROM access_token WHERE token = $1
`

func (q *Queries) GetAccessToken(ctx context.Context, token string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessToken, token)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
		&i.Revoked,
	)
	return i, err
}

const getFestivalAccess = `-- name: GetFestivalAccess :one
SELECT id, festival_id, last_used_at, user_id
FROM festival_access
WHERE user_id = $1 AND festival_id = $2
`

type GetFestivalAccessParams struct {
	UserID     int64 `json:"user_id"`
	FestivalID int64 `json:"festival_id"`
}

type GetFestivalAccessRow struct {
	ID         int64 `json:"id"`
	FestivalID int64 `json:"festival_id"`
	LastUsedAt int64 `json:"last_used_at"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) GetFestivalAccess(ctx context.Context, arg GetFestivalAccessParams) (GetFestivalAccessRow, error) {
	row := q.db.QueryRow(ctx, getFestivalAccess, arg.UserID, arg.FestivalID)
	var i GetFestivalAccessRow
	err := row.Scan(
		&i.ID,
		&i.FestivalID,
		&i.LastUsedAt,
		&i.UserID,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, revoked
FROM refresh_token WHERE token = $1
`

type GetRefreshTokenRow struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	Revoked   bool   `json:"revoked"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getUserIdFromAccessToken = `-- name: GetUserIdFromAccessToken :one
SELECT user_id FROM access_token WHERE token = $1
`

func (q *Queries) GetUserIdFromAccessToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIdFromAccessToken, token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserRecentSessions = `-- name: GetUserRecentSessions :many
SELECT f.code, fa.last_used_at
FROM festival_access fa
JOIN festival f ON f.id = fa.festival_id
WHERE fa.user_id = $1 AND fa.revoked = false
ORDER BY fa.last_used_at DESC
LIMIT $2 OFFSET $3
`

type GetUserRecentSessionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserRecentSessionsRow struct {
	Code       string `json:"code"`
	LastUsedAt int64  `json:"last_used_at"`
}

func (q *Queries) GetUserRecentSessions(ctx context.Context, arg GetUserRecentSessionsParams) ([]GetUserRecentSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentSessions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentSessionsRow
	for rows.Next() {
		var i GetUserRecentSessionsRow
		if err := rows.Scan(&i.Code, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessToken = `-- name: UpdateAccessToken :exec
UPDATE access_token SET expires_at = $1, revoked = $2 WHERE id = $3
`

type UpdateAccessTokenParams struct {
	ExpiresAt int64 `json:"expires_at"`
	Revoked   bool  `json:"revoked"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateAccessToken(ctx context.Context, arg UpdateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, updateAccessToken, arg.ExpiresAt, arg.Revoked, arg.ID)
	return err
}

const updateFestivalAccessLastUsedAt = `-- name: UpdateFestivalAccessLastUsedAt :exec
UPDATE festival_access SET last_used_at = $1 WHERE id = $2
`

type UpdateFestivalAccessLastUsedAtParams struct {
	LastUsedAt int64 `json:"last_used_at"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateFestivalAccessLastUsedAt(ctx context.Context, arg UpdateFestivalAccessLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateFestivalAccessLastUsedAt, arg.LastUsedAt, arg.ID)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_token SET expires_at = $1, revoked = $2 WHERE id = $3
`

type UpdateRefreshTokenParams struct {
	ExpiresAt int64 `json:"expires_at"`
	Revoked   bool  `json:"revoked"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.ExpiresAt, arg.Revoked, arg.ID)
	return err
}
