FROM golang:1.25-alpine AS builder

RUN apk add --no-cache build-base

WORKDIR /app

COPY . .

WORKDIR /app/cleanup

RUN go mod download

RUN go build -o cleanup -ldflags="-s -w" ./cmd/main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/cleanup/cleanup /app/cleanup

RUN chmod +x /app/cleanup

CMD ["./cleanup"]
